export const CHAINS = [
  {
    name: 'ETHEREUM',
    rpc: 'https://eth-rpc.gateway.pokt.network',
    chainId: 1,
    currency: 'ETH',
    explorer: 'https://etherscan.io',
  },
  {
    name: 'ARBITRUM',
    rpc: 'https://arbitrum-one.public.blastapi.io',
    chainId: 42161,
    currency: 'ETH',
    explorer: 'https://arbiscan.io',
  },
  {
    name: 'OPTIMISM',
    rpc: 'https://optimism-mainnet.public.blastapi.io',
    chainId: 10,
    currency: 'ETH',
    explorer: 'https://optimistic.etherscan.io',
  },
  {
    name: 'ZKSYNC',
    rpc: 'https://mainnet.era.zksync.io',
    chainId: 324,
    currency: 'ETH',
    explorer: 'https://explorer.zksync.io',
  },
  {
    name: 'POLYGON',
    rpc: 'https://polygon.llamarpc.com',
    chainId: 137,
    currency: 'MATIC',
    explorer: 'https://polygonscan.com',
  },
  {
    name: 'BSC',
    rpc: 'https://rpc.ankr.com/bsc',
    chainId: 56,
    currency: 'BNB',
    explorer: 'https://bscscan.com',
  },
  {
    name: 'AVALANCHE',
    rpc: 'https://avalanche.blockpi.network/v1/rpc/public',
    chainId: 43114,
    currency: 'AVAX',
    explorer: 'https://snowtrace.io',
  },
  {
    name: 'BASE',
    rpc: 'https://base.llamarpc.com',
    chainId: 8453,
    currency: 'ETH',
    explorer: '',
  },
  {
    name: 'GNOSIS',
    rpc: 'https://gnosis.drpc.org',
    chainId: 100,
    currency: 'XDAI',
    explorer: '',
  },
  {
    name: 'ZKEVM',
    rpc: 'https://polygon-zkevm-mainnet.public.blastapi.io',
    chainId: 1101,
    currency: 'ETH',
    explorer: '',
  },
  {
    name: 'AURORA',
    rpc: 'https://mainnet.aurora.dev',
    chainId: 1313161554,
    currency: 'ETH',
    explorer: '',
  },
];
