export const CHAINS = [
  {
    name: 'Ethereum',
    rpc: 'https://eth.llamarpc.com',
    chainId: 1,
    currency: 'ETH',
    explorer: 'https://etherscan.io',
  },
  {
    name: 'Arbitrum One',
    rpc: 'https://arbitrum-one.public.blastapi.io',
    chainId: 42161,
    currency: 'ETH',
    explorer: 'https://arbiscan.io',
  },
  {
    name: 'Optimism',
    rpc: 'https://optimism-mainnet.public.blastapi.io',
    chainId: 10,
    currency: 'ETH',
    explorer: 'https://optimistic.etherscan.io',
  },
  {
    name: 'ZkSync Era',
    rpc: 'https://mainnet.era.zksync.io',
    chainId: 324,
    currency: 'ETH',
    explorer: 'https://explorer.zksync.io',
  },
  {
    name: 'Polygon',
    rpc: 'https://polygon.llamarpc.com',
    chainId: 137,
    currency: 'MATIC',
    explorer: 'https://polygonscan.com',
  },
  {
    name: 'Binance Smart Chain',
    rpc: 'https://rpc.ankr.com/bsc',
    chainId: 56,
    currency: 'BNB',
    explorer: 'https://bscscan.com',
  },
  {
    name: 'Avalanche (C-Chain)',
    rpc: 'https://avalanche.blockpi.network/v1/rpc/public',
    chainId: 43114,
    currency: 'AVAX',
    explorer: 'https://snowtrace.io',
  },
  {
    name: 'Base',
    rpc: 'https://base.llamarpc.com',
    chainId: 8453,
    currency: 'ETH',
    explorer: '',
  },
];
