import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="flex min-h-screen flex-col items-center justify-center p-24">
          <div className="flex flex-col justify-center items-center">{children}</div>
        </main>
        <footer className="border-t border-t-slate-700 w-full font-mono ">
          <div className="flex justify-center text-lg py-4">Made by @maksympanchyshyn</div>
        </footer>
      </body>
    </html>
  );
}
